version: "3"
services:
  congee-mockup:
    build: .
    ports:
      - "5000:5000"
    environment:
      - CERT_FILE=/certs/congee.mockup.crt
      - KEY_FILE=/certs/congee.mockup.key
    volumes:
      - ./certs/congee.mockup.crt:/certs/congee.mockup.crt
      - ./certs/congee.mockup.key:/certs/congee.mockup.key
